name = "Hugo Shourya Winston"
license = "MIT"
licenselink = "https://github.com/shouryaps/hugo-shourya-winston-theme/blob/master/LICENSE"
description = " Blog theme powering shouryaps.com"

homepage = "https://github.com/shouryaps/hugo-shourya-winston-theme"
demosite = "https://shouryaps.com"

tags = ["blog"]
features = ["blog"]

[author]
  name = "Shourya Pratap Singh"
  homepage = "https://shouryaps.com"

[original]
  name = "Robert Austin"
  homepage = "https://www.zerostatic.io"