baseURL = "https://shouryaps.com/"
languageCode = "en-us"
title = "@shouryaps"
themesDir = "../.."
theme = "hugo-shouryaps-blog-theme"

paginate = 5

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  twitterHandle = "@shouryaps"

  twitterUsername = "shouryaps"
  linkedinUsername = "shouryaps"
  githubUsername = "shouryaps"
  email = "mail@shouryaps.com"

  ccLicenseURL = "https://creativecommons.org/licenses/by-nc-sa/4.0/"
  
  introMD= "**Shourya's** Home on Internet"

  showPostsOnHomepage = true
  maxHomepagePosts = 2
  showAuthorNameOnPosts = false

  addFrame = true
  addDot = true

  highlightColor = '#7b16ff'

[taxonomies]
    tag = "tags"