baseURL = "https://shouryaps.com/"
languageCode = "en-us"
title = "Shourya Pratap Singh"
themesDir = "../.."
theme = "hugo-shourya-winston-theme"

paginate = 5

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  twitterHandle = "@shouryaps"
  twitterUsername = "shouryaps"

  logoTitle = "@shouryaps"

  showAuthorOnPosts = true

  addFrame = true
  addDot = true

  highlightColor = '#7b16ff'

[taxonomies]
    tag = "tags"